import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { VitePWA } from 'vite-plugin-pwa'

export default defineConfig({
  plugins: [
    react(),
    VitePWA({
      registerType: 'autoUpdate',
      // Icons already live in /public/icons — nothing here needs to be
      // generated by the plugin itself, just declared in the manifest below.
      includeAssets: ['icons/favicon-32.png', 'icons/apple-touch-icon.png'],
      manifest: {
        name: 'RideIN — Keke rides for your estate',
        short_name: 'RideIN',
        description:
          'Book a verified keke ride within your estate, choose your rider, and pay by bank transfer — no cash, no guessing.',
        start_url: '/',
        scope: '/',
        display: 'standalone',
        // Matches the app's dark hero background so the OS splash screen
        // (shown for a moment right after tapping the home-screen icon)
        // doesn't flash white before the app itself paints.
        background_color: '#2f4b43',
        theme_color: '#1F4E43',
        icons: [
          { src: '/icons/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
          { src: '/icons/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
          { src: '/icons/maskable-192.png', sizes: '192x192', type: 'image/png', purpose: 'maskable' },
          { src: '/icons/maskable-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
        ],
      },
      workbox: {
        // Precache the built app shell (JS/CSS/HTML/icons) so the app can
        // still open offline — but never precache or cache API responses:
        // ride/payment/notification data must always come from the network,
        // never a stale cached copy, so this deliberately has NO runtime
        // caching rule for api.ridein.ng.
        navigateFallback: '/index.html',
        globPatterns: ['**/*.{js,css,html,svg,png,ico}'],
      },
      devOptions: {
        // Keep the service worker out of `npm run dev` — it's a
        // production-build concern, and having it active during
        // development is how people get stuck on old cached code.
        enabled: false,
      },
    }),
  ],
})
